enum typeenums {
  INIT_CHAT = 'INITCHAT',
  PUSH_CHAT = 'PUSH_CHAT',
  USER_SEND_MSG = 'USER_SEND_MSG',
  CHANGE_CHAT = 'CHANGE_CHAT',
  PUSH_NEWCHAT_MSG = 'PUSH_NEWCHAT_MSG',
  GET_BRAIN_REPLY = 'GETBRAINREPLY',
  START_GET_REPLY = 'START_GET_REPLY',
  UPDATEASSISTANTMSG = 'UPDATEASSISTANTMSG',
  SUCCESS_GET_REPLY = 'SUCCESS_GET_REPLY',
  END_GET_REPLY = 'END_GET_REPLY',
  SET_OPENAI_KEY = 'SET_OPENAI_KEY',
  APPSET = 'APP_SET',
  SHOWOPENAISETKEY = 'SHOWOPENAISETKEY',
  SHOWPRE = 'SHOWPRE'
}

export default typeenums